### ISSUE TITLE
Can't upload anything, because there is no such option.

### ISSUE THREAD

**Issue by Hiieu** [smacker/django-filebrowser-no-grappelli#11]
No buttons.

Chrome:

http://i.imgur.com/upCAYuM.png

**Comment by smacker** [comment]
Django version, filebrowser version, browser?

Just tested it with django 1.7, filebrowser from master brunch and safari.

![screen shot 2015-01-11 at 3 59 00 pm](https://cloud.githubusercontent.com/assets/406916/5695011/ecdddc6a-99aa-11e4-9ed7-c84d3f2e8043.png)

**Comment by Hiieu** [comment]
Ok, I tried on FireFox and it seems working fine, but somehow it doesn't on chrome.

![Image ff](http://i.imgur.com/Bx0Tw3F.png)

**Comment by igorkud90** [comment]
I do not see this button in chrome

**Comment by smacker** [comment]
I think some plugin (adblock, flashblock, ...) in your chrome blocks something therefore there no button. Works for me.

**Comment by AlwaysYou** [comment]
Thank you @smacker.
it works for me (:
