### ISSUE TITLE
Delete Checkbox, how to show that?

### ISSUE THREAD

**Issue by sunjoomoon** [smacker/django-filebrowser-no-grappelli#17]
Somehow delete checkbox is not shown in the chanagelist, I am using FileBrowser 3.6.1 with django 1.8.7. Anybody has any clues as to what to look into?

**Comment by smacker** [comment]
Are you talking about checkbox to delete many files at once?
Upstream (https://github.com/sehmaschine/django-filebrowser) doesn't support bulk delete.

**Comment by sunjoomoon** [comment]
Yes, bulk delete. Hope to see this feature someday. Cheers.
