### ISSUE TITLE
Not technically 1.9 compliant

### ISSUE THREAD

**Issue by marc-gist** [smacker/django-filebrowser-no-grappelli#23]
You have a number of RemovedInDjango110Warning messages:

`RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
  return template.render(context, request)`

you use RequestContext in a number of places.

and:

`sites.py:340: RemovedInDjango110Warning: The current_app argument of RequestContext is deprecated. Set the current_app attribute of its request instead.
  }, request), context_instance=Context(request, current_app=self.name))`

also sill need to fix SubfieldBase warnings. the pull request that claims to fix this doesn't work.

Thanks for the great work... I have spent some time trying to figure out how to fix these, but don't really have a clue... hopefully you can find some time to make the changes.

**Comment by marc-gist** [comment]
also sill need to fix SubfieldBase warnings. the pull request that claims to fix this doesn't work.

**Comment by marc-gist** [comment]
I think I have compensated for the change... likely won't be compliant with <1.8, but seems to work fine for 1.9.2.

https://github.com/marc-gist/django-filebrowser-no-grappelli/commit/784e9c049b92be0bdc51875c37795a50f9a9266e 

I made significant changes to the template files for bootstrap 3 compatibility, so not sure I can make a proper pull request.

**Comment by smacker** [comment]
Warnings are not errors. You can disable them in production by setting correct log report level and everything will work fine.

I fixed the easiest warnings, but for context it's a little bit more complicated. I'll fix it too but can't say when yet.
And about SubfieldBase. Thanks for report. I'll take a look at PR and accept/fix it in few days.

**Comment by smacker** [comment]
django-filebrowser-no-grappelli 3.7.0 released. It supports django 1.8/1.9/1.10
