### ISSUE TITLE
Folders being listed as selectable and 'format' not working correctly.

### ISSUE THREAD

**Issue by FilippoIOVINE** [smacker/django-filebrowser-no-grappelli#29]
Hi,
Having **filter_type** instead **type** var in templates/filebrowser/custom_field.html line 2, causes wrong rendering of the file list (e.g. "select" even for folders type).

![image](https://cloud.githubusercontent.com/assets/5149320/23128986/44b6689a-f781-11e6-9069-2656c8d8ac58.png)

**Comment by FilippoIOVINE** [comment]
My mistake: when defining a FileBrowseField I need to set even a **format** param:
image = FileBrowseField(blank=True, null=True, max_length=200, directory='images/', extensions=['.jpg', '.png'], format='image')
otherwise folders are selectable too.
Just wondering if this is the correct behaviour then.

**Comment by FilippoIOVINE** [comment]
I was not wrong:
https://github.com/sehmaschine/django-filebrowser/pull/324
Btw, previous version of django-filebrowser-no-grappelli was ok.

**Comment by smacker** [comment]
The change was done here: https://github.com/sehmaschine/django-filebrowser/pull/308
it isn't a problem for you now, right? I'm not sure which behavior is correct, so it works just as in a upstream. If upstream would change it, it will be changed here too.

**Comment by FilippoIOVINE** [comment]
Thanks @smacker.
it is a problem for me because I need to let customers select just images and not folders or other type of files.
I have overridden two templates (custom_upload_field.html and custom_field.html) and restored correct behaviour (IMHO).
Anyway I guess type and filter_type are not working the way they should be. Still investigating but they look a bit fuzzy.

**Comment by smacker** [comment]
Oh. I have been confused by "filter_type" option that also filters types. Fixed in master.
