### ISSUE TITLE
Missing newest releases

### ISSUE THREAD

**Issue by tuxredux** [smacker/django-filebrowser-no-grappelli#30]
Where is the source code for the newest releases `3.6.2` and `3.7.0`... ? I'm trying to override the templates to add [django-material](https://github.com/viewflow/django-material) admin support and I'm coming across `TemplateSyntaxError`s, but then I realized I was using `3.5.8` templates with my currently installed `3.7.0` version. I can get the templates from the locally installed library, but I was just wondering if the remote provider changed or if this library is no longer being maintained? Thanks in advance for your time.

**Comment by smacker** [comment]
Templates for v3.7.0 are here: https://github.com/smacker/django-filebrowser-no-grappelli/tree/e8511a95cf4f328cd46ff184a02a91f93b0cacd5

I'll create tags for versions and release v.3.7.1 from master branch soon. Sorry for inconvenience.

**Comment by tuxredux** [comment]
@smacker No worries! I appreciate your work. Cheers! :smile:

**Comment by smacker** [comment]
Version 3.7.1 has been released.
I also created tags for 3.7.0 & 3.6.2.
