### ISSUE TITLE
upload file not showing?

### ISSUE THREAD

**Issue by mLouie22** [smacker/django-filebrowser-no-grappelli#33]
Hello,

I'm pretty new in django and python

I tried using the origin filebrowser (with grappelli)
everything is fine but I personally don't like the style in grappelli

then I found this! I tried immediately and glad it's working except the upload button is not showing

I tried using other browsers, created new project, turning off adblock nothing seems working for me

![image](https://user-images.githubusercontent.com/31334345/30573880-f3f91c38-9d28-11e7-896d-ef64bfcc53f1.png)

**Comment by smacker** [comment]
please check your configuration. Most probably something is wrong with config for static files. You can open dev tools and see failed requests to js files. You can read more about static files in django in official documentation https://docs.djangoproject.com/en/1.11/howto/static-files/
