### ISSUE TITLE
./manage.py dumpdata fails for FileBrowseField with Django2.0 and SQLite

### ISSUE THREAD

**Issue by gbezyuk** [smacker/django-filebrowser-no-grappelli#37]
Using Django 2.0.1, I can't dump FileBrowseFields:

```bash
(venv) ➜  backend git:(master) ✗ ./manage.py dumpdata some.Model --indent=2 > dump.json
CommandError: Unable to serialize database: 'FileBrowseField' object has no attribute '_get_val_from_obj'
Exception ignored in: <generator object cursor_iter at 0x1065b0048>
Traceback (most recent call last):
  File "/w/some-project/backend/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1460, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by waustin** [comment]
I'm getting a similar error with dumpdata on Django 2.0 and Postgres. 

CommandError: Unable to serialize database: 'FileBrowseField' object has no attribute '_get_val_from_obj'

I believe the method '_get_val_from_obj' was removed in Django 2.0.

**Comment by smacker** [comment]
oh, sorry guys. I missed the issue. Will review later today/tomorrow.

**Comment by smacker** [comment]
Fixed by @waustin with https://github.com/smacker/django-filebrowser-no-grappelli/pull/38

**Comment by smacker** [comment]
version 3.7.4 is on pypi.
