### ISSUE TITLE
FileBrowseWidget.render() needs a renderer kwarg for Django 2.1

### ISSUE THREAD

**Issue by vdboor** [smacker/django-filebrowser-no-grappelli#41]
To fix Django 2.1 compatibilty, the `FileBrowseWidget.render()` needs a `renderer` kwarg. Other then that, I didn't find any Django 2.1 issues on first sight.

**Comment by smacker** [comment]
Thank you for checking the compatibility with new Django! I’ll try to fix it next week.

**Comment by smacker** [comment]
fixed by #44
