### ISSUE TITLE
Design of iframe with TinyMCE

### ISSUE THREAD

**Issue by ggjersund** [smacker/django-filebrowser-no-grappelli#48]
Am I doing something wrong, or if this is the design for using it with TinyMCE?
[Image of iframe in admin panel with TinyMCE](https://imgur.com/a/Rr6oRJY)

**Comment by smacker** [comment]
Something is wrong. Most probably filebrowser css isn't loaded. Please check that serving static works correctly.

**Comment by smacker** [comment]
This issue isn't reproducible and most probably caused by misconfiguration.

I'm closing it. But feel free to reopen if you have steps to reproduce it! Thanks.
