### ISSUE TITLE
how to set language

### ISSUE THREAD

**Issue by welldone217** [smacker/django-filebrowser-no-grappelli#54]
it is english for me .i want  chinese.

**Comment by smacker** [comment]
Please take a look at django documentation to see how to set the language: https://docs.djangoproject.com/en/2.0/ref/settings/#language-code

django-filebrowser will use the same language automatically.

Feel free to re-open the issue if the languages of django and file browser don't match.

**Comment by welldone217** [comment]
the Django2.1 LANGUAGE_CODE = 'zh-Hans'  is ok。but django-filebrowser is English.

**Comment by smacker** [comment]
Thank you for the bug report!
I have fixed it in master: https://github.com/smacker/django-filebrowser-no-grappelli/commit/3f1d0e303c7eee64dd356376c7d3e74544dba882

I'll do the release tomorrow.

**Comment by welldone217** [comment]
ok，3Q

**Comment by smacker** [comment]
v3.7.8 released: https://pypi.org/project/django-filebrowser-no-grappelli/#history
