### ISSUE TITLE
Local URI issue

### ISSUE THREAD

**Issue by MarioBG** [smacker/django-filebrowser-no-grappelli#59]
I'm developing a system in which I need the Django site to interface with a Unity-developed application, where the Django app acts, among other things, as a provider for some images. I found this plugin for uploading and managing the images, but I'm having some issues with displaying the images within the Filebrowser views. Basically, it's adding the URL stored in the database to the whole path to the current view, so instead of linking and displaying the image at 'localhost/static/foo/bar.png', if I'm at 'localhost/admin/users/1/change', it tries to display a theoretical image at 'localhost/admin/users/1/static/foo/bar.png'. Attached you can find a real example of this.

![image](https://user-images.githubusercontent.com/1349152/65137838-4eea0b00-da0a-11e9-949f-4d6d0ea7455e.png)

Thanks for your attention, and I look forward to your answer.

**Comment by smacker** [comment]
Hi @MarioBG !
Please validate your setting of `MEDIA_URL`. You can get more information from [django documentation](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-MEDIA_URL).
