### ISSUE TITLE
When is TinyMCE V5 supported?

### ISSUE THREAD

**Issue by wangyushun** [smacker/django-filebrowser-no-grappelli#62]
I used TinyMCE(V5) and Django-filebrowser-no-grappelli(v3.8.0), they can't work well, and I've spent a lot of time on it.Because TinyMCE V5 is not supported yet. Now, a new pull request ([support for TinyMCE v5](https://github.com/sehmaschine/django-filebrowser/pull/382))  submitted by [alan-hicks](https://github.com/alan-hicksrl) . I added the changes to my project and it worked.

**Comment by oruehenbeck** [comment]
done in https://github.com/smacker/django-filebrowser-no-grappelli/pull/67
