### ISSUE TITLE
Incompatibility with django 3.1.2

### ISSUE THREAD

**Issue by christianwgd** [smacker/django-filebrowser-no-grappelli#66]
Django 3.1.2 changed the [changelist.css](https://github.com/django/django/commit/57b359343bb3ee733ec8dfaf40be55be4d6d3c5d) to flex layout. This destroys the layout of the filebrowser admin changelist. This is especially annoying in the popup windows like tinymce.

<img width="400" alt="django3_1_1" src="https://user-images.githubusercontent.com/9281647/95575127-74d7b880-0a2e-11eb-90ad-054a57dae5f6.png">(Before: Django 3.1.1)

<img width="400" alt="django3_1_2" src="https://user-images.githubusercontent.com/9281647/95575107-6c7f7d80-0a2e-11eb-8e56-b67be87240e4.png">(After: Django3.1.2)

**Comment by bloodwithmilk25** [comment]
I can't rollback to django 3.0.x so had to add this style to `extrastyle` block in my base_site.html
```
{% block extrastyle %}
     <style type="text/css">
          #changelist {
              flex-direction: column;
          }
     </style>
{% endblock %}
```
It fixes the issue and seem like it's not braking anything else in the admin.

**Comment by smacker** [comment]
fixed in the new release https://pypi.org/project/django-filebrowser-no-grappelli/4.0.0/
