### ISSUE TITLE
Page not found / table filebrowser_filebrowser doesn't exist

### ISSUE THREAD

**Issue by lguariento** [smacker/django-filebrowser-no-grappelli#71]
Hello,

I'm using django-filebrowser-no-grappelli version 3.8.0 with Django 3.2.4.

I have `path('admin/filebrowser/', site.urls),` in my `urls.py`.

At some point recently (I cannot say precisely when, I just discovered it) it the admin 'browse' section stopped working. It used to work when I first installed months ago.

When I go to `admin/filebrowser/browse/` I get 

```
<h1>Page not found <span>(404)</span></h1>
Request Method: | GET
-- | --
/admin/filebrowser/browse/
django.contrib.admin.sites.catch_all_view
```

When I launch `python manage.py dumpdata > db.json` I get:

```
CommandError: Unable to serialize database: (1146, "Table 'NMS_database.filebrowser_filebrowser' doesn't exist")
```

What can the reason be?

**Comment by vdboor** [comment]
I've seen the same thing, this seems to happen due to changes in Django 3.2. Projects with Django 3.1 work fine.

**Comment by lguariento** [comment]
I'm glad to hear I'm not the only one. It would be great if it worked with the latest versions.

**Comment by smacker** [comment]
@lguariento I believe something is wrong with your configuration. You can try to create a new clean project, add filebrowser, ensure it works, and then compare it with your existing project to see where is the problem.
