### ISSUE TITLE
Upload template points at minified JS file that was removed at django 3.2

### ISSUE THREAD

**Issue by andylolz** [smacker/django-filebrowser-no-grappelli#75]
admin/js/collapse.min.js is referenced here:
https://github.com/smacker/django-filebrowser-no-grappelli/blob/310e0272b2f9400861c27b3b2174f10d8cc74372/filebrowser/templates/filebrowser/upload.html#L18

This minified file was removed at django 3.2:
https://docs.djangoproject.com/en/3.2/releases/3.2/#id1

> Minified JavaScript files are no longer included with the admin. If you require these files to be minified, consider using a third party app or external build tool. The minified vendored JavaScript files packaged with the admin (e.g. [jquery.min.js](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#contrib-admin-jquery)) are still included.

It would be forwards and backwards compatible to instead reference the unminified version here.

**Comment by smacker** [comment]
I released the new version with your fix: https://pypi.org/project/django-filebrowser-no-grappelli/#history

file-browser 4 dropped old django versions so I think we can just require v3.2 as the new minimal compatible django.
