### ISSUE TITLE
Pillow deprecations - e.g. ANTIALIAS

### ISSUE THREAD

**Issue by christianwgd** [smacker/django-filebrowser-no-grappelli#79]
Some constants are deprecated in Pillow 9 and will be removed in future versions. At the moment we get some deprecation warnings like: 

`ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.`

The full list of deprecations can be seen here: https://pillow.readthedocs.io/en/stable/deprecations.html#constants

**Comment by irodweb4** [comment]
Rub****
